---
- name: bootstrapping
  hosts: raiders
  gather_facts: no

  vars:
    newusers:
    - marian
    - belloq
    - willie
    - elsa

  tasks:
  - name: update apt with latest repo info
    raw: "apt update -y"
    become: yes

  - name: install py3 and pip3 with ansible raw
    raw: "apt install -y python3-pip"
    become: yes

  - name: create new group
    group:
      name: indymovies
      state: present
    become: yes
  
  - name: Add new user
    user:
       name: "{{ item }}"
       state: present
       group: indymovies
    become: yes
    loop: "{{ newusers }}"

